In [1]:
import numpy as np

In [2]:
data=np.random.randint(0,10,(3,3))
data

array([[2, 6, 2],
       [4, 3, 3],
       [4, 3, 3]])

In [3]:
data.sum()

np.int64(30)

In [4]:
data.sum(axis=1)

array([10, 10, 10])

In [5]:
data.sum(axis=0)

array([10, 12,  8])

In [6]:
data.max()

np.int64(6)

In [7]:
data.max(axis=1)

array([6, 4, 4])

In [8]:
data.argmax(axis=1)

array([1, 0, 0])

In [12]:
data=np.random.randint(0,100,(10,5))
data

array([[49, 79, 68, 89, 36],
       [81, 24, 93, 67,  2],
       [26, 55, 44, 93, 79],
       [74, 52, 67, 15, 47],
       [22, 94,  2, 85, 52],
       [38, 92, 67, 47, 28],
       [54, 46, 69, 14,  3],
       [46, 91, 43, 31, 30],
       [87, 42,  6, 33, 84],
       [60, 61, 58, 26, 63]])

In [13]:
data.sum(axis=1)

array([321, 267, 297, 255, 255, 272, 186, 241, 252, 268])

In [14]:
data.sum(axis=1).argmin()+1

np.int64(7)

In [15]:
data.sum(axis=1)

array([321, 267, 297, 255, 255, 272, 186, 241, 252, 268])

In [16]:
data.sum(axis=1)

array([321, 267, 297, 255, 255, 272, 186, 241, 252, 268])

In [17]:
data.sum(axis=0)

array([537, 636, 517, 500, 424])

In [18]:
data.sum()

np.int64(2614)

In [20]:
data=np.random.randint(10,100,(10,5))
data

array([[33, 35, 21, 51, 10],
       [31, 77, 73, 54, 86],
       [50, 48, 36, 96, 17],
       [26, 55, 38, 69, 91],
       [11, 45, 88, 40, 71],
       [18, 72, 11, 89, 29],
       [10, 45, 34, 51, 70],
       [65, 11, 18, 78, 69],
       [33, 74, 24, 64, 43],
       [92, 49, 40, 56, 62]])

In [21]:
data.sum(axis=0).argmax()+1


np.int64(4)

In [22]:
data.sum(axis=0)

array([369, 511, 383, 648, 548])

In [23]:
data.sum(axis=0)[3:].sum()

np.int64(1196)

In [24]:

data[:,3:5].sum()

np.int64(1196)

In [25]:
data.sum(axis=0).max()

np.int64(648)

In [26]:
data.sum(axis=0).min()

np.int64(369)

In [27]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(279)

In [28]:
data=np.random.randint(0,10,10)
data

array([5, 5, 6, 3, 2, 4, 8, 8, 8, 5])

In [30]:
data.mean()

np.float64(5.4)

In [33]:
np.median(data)

np.float64(5.0)

In [34]:
np.quantile(data,0.25)

np.float64(4.25)

In [35]:
np.quantile(data,0.75)

np.float64(7.5)

In [36]:
np.quantile(data,0.50)

np.float64(5.0)

In [37]:
np.median(data)

np.float64(5.0)

In [38]:
np.std(data)

np.float64(2.0099751242241783)

In [39]:
data=np.random.randint(0,10,(10,2))

In [40]:
np.corrcoef(data.T)

array([[ 1.        , -0.23210746],
       [-0.23210746,  1.        ]])

In [43]:
v1=np.arange(1,11)
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
v2=np.arange(10,20)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
x=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [47]:
data[:,0]=v1
data[:,1]=v2
v1+v2

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [48]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [50]:
data=np.random.randint(0,10,(5,5))

In [51]:
np.corrcoef(data)
data

array([[6, 5, 6, 8, 8],
       [0, 3, 3, 5, 9],
       [4, 6, 3, 1, 2],
       [0, 6, 0, 1, 4],
       [5, 8, 7, 4, 8]])