In [1]:
import numpy as np

# Retail dataset as numpy array
retail_np_array = np.array([
    [1001, "Laptop", 1, 50000, 50000],
    [1002, "Mouse", 2, 500, 1000],
    [1003, "Keyboard", 1, 1000, 1000],
    [1004, "Monitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000]
], dtype=object)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [2]:
type(retail_np_array[0,2])

int

In [3]:

quantities = retail_np_array[:, 2].astype(int)
prices = retail_np_array[:, 3].astype(int)
totals = retail_np_array[:, 4].astype(int)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [4]:
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [5]:
 retail_np_array.size

25

In [6]:
 retail_np_array.shape[0]

5

In [7]:

customer_ids = retail_np_array[:, 0]
products = retail_np_array[:, 1]
quantities = retail_np_array[:, 2].astype(int)
prices = retail_np_array[:, 3].astype(int)
totals = retail_np_array[:, 4].astype(int)
retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [12]:

# Compute answers using NumPy
answers_np = {
    "1. Total number of transactions": retail_np_array.shape[0],
    "2. Total revenue generated": np.sum(totals),



    "3. Average order value": np.mean(totals),
    "4. Product with the highest total price": products[np.argmax(totals)],
    "5. Product with the lowest total price": products[np.argmin(totals)],
    "6. Average price of products": np.mean(prices),
    "7. Total quantity sold": np.sum(quantities),
    "8. Most frequently purchased product": np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])],
    "9. Number of unique products": len(np.unique(products)),
    "10. Number of unique customers": len(np.unique(customer_ids)),
    "11. List all products sold": products.tolist(),
    "12. Revenue per product": {prod: np.sum(totals[products == prod]) for prod in np.unique(products)},
    "13. Quantity sold per product": {prod: np.sum(quantities[products == prod]) for prod in np.unique(products)},
    "14. Highest price of a product": np.max(prices),
    "15. Lowest price of a product": np.min(prices),
    "16. Products sold more than once": products[quantities > 1].tolist(),
    "17. Customers who bought more than one item": customer_ids[quantities > 1].tolist(),
    "18. Total spent by CustomerID 1002": np.sum(totals[customer_ids == 1002]),
    "19. Products priced above 1000": products[prices > 1000].tolist(),
    "20. Products with total >= 2000": products[totals >= 2000].tolist()
}

answers_np


{'1. Total number of transactions': 5,
 '2. Total revenue generated': np.int64(68000),
 '3. Average order value': np.float64(13600.0),
 '4. Product with the highest total price': 'Laptop',
 '5. Product with the lowest total price': 'Mouse',
 '6. Average price of products': np.float64(12100.0),
 '7. Total quantity sold': np.int64(7),
 '8. Most frequently purchased product': 'Headphones',
 '9. Number of unique products': 5,
 '10. Number of unique customers': 5,
 '11. List all products sold': ['Laptop',
  'Mouse',
  'Keyboard',
  'Monitor',
  'Headphones'],
 '12. Revenue per product': {'Headphones': np.int64(2000),
  'Keyboard': np.int64(1000),
  'Laptop': np.int64(50000),
  'Monitor': np.int64(14000),
  'Mouse': np.int64(1000)},
 '13. Quantity sold per product': {'Headphones': np.int64(1),
  'Keyboard': np.int64(1),
  'Laptop': np.int64(1),
  'Monitor': np.int64(2),
  'Mouse': np.int64(2)},
 '14. Highest price of a product': np.int64(50000),
 '15. Lowest price of a product': np.int64(500

In [13]:
np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])]

'Headphones'

In [14]:
np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])]

'Headphones'

In [15]:

products.tolist()


['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones']

In [16]:
products

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
      dtype=object)