In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,5)

In [ ]:
data

array([9, 8, 6, 5, 3])

In [ ]:
data+3

array([12, 11,  9,  8,  6])

In [ ]:
x=np.random.randint(0,10,(4,3))

In [ ]:
x

array([[2, 6, 7],
       [7, 5, 8],
       [0, 3, 3],
       [6, 1, 1]])

In [ ]:
y=np.random.randint(0,10,(1,3))

In [ ]:
x

array([[2, 6, 7],
       [7, 5, 8],
       [0, 3, 3],
       [6, 1, 1]])

In [ ]:
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]
[7, 1, 3]

In [ ]:
y

array([[7, 1, 3]])

In [ ]:
x+y

array([[ 9,  7, 10],
       [14,  6, 11],
       [ 7,  4,  6],
       [13,  2,  4]])

In [ ]:
x=np.random.randint(0,10,(4,1))

In [ ]:
x

array([[5],
       [1],
       [1],
       [5]])

In [ ]:
y=np.random.randint(0,10,4)

In [ ]:
x

array([[5],
       [1],
       [1],
       [5]])

In [ ]:
y

array([3, 3, 9, 9])

In [ ]:
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]
[3, 3, 9, 9]

[3, 3, 9, 9]

In [ ]:
5555
1111
1111
5555


In [ ]:
x+y

array([[ 8,  8, 14, 14],
       [ 4,  4, 10, 10],
       [ 4,  4, 10, 10],
       [ 8,  8, 14, 14]])

In [ ]:
x

array([[5],
       [1],
       [1],
       [5]])

In [ ]:
y

array([3, 3, 9, 9])

In [ ]:
### Link :https://numpy.org/devdocs//user/basics.broadcasting.html

In [ ]:
import numpy as np

In [ ]:
data=np.loadtxt("/content/sample.txt")

In [ ]:
data

array([[12., 45., 78., 23., 56.],
       [34., 67., 89., 12., 90.],
       [56., 21., 43., 65., 87.],
       [78., 34., 12., 89., 23.],
       [90., 11., 67., 32., 45.],
       [14., 58., 29., 71., 63.],
       [32., 84., 91., 17., 55.],
       [46., 38., 27., 66., 49.],
       [53., 72., 19., 88., 30.],
       [61., 40., 76., 35., 20.]])

In [ ]:
data.shape

(10, 5)

In [ ]:
import glob

In [ ]:
/content/

['/content/sample file.txt',
 '/content/sample file2.txt',
 '/content/sample.txt']

In [ ]:
data

array([[12., 45., 78., 23., 56.],
       [34., 67., 89., 12., 90.],
       [56., 21., 43., 65., 87.],
       [78., 34., 12., 89., 23.],
       [90., 11., 67., 32., 45.],
       [14., 58., 29., 71., 63.],
       [32., 84., 91., 17., 55.],
       [46., 38., 27., 66., 49.],
       [53., 72., 19., 88., 30.],
       [61., 40., 76., 35., 20.]])

In [ ]:
x=2
x**2

4

In [ ]:
[4,2,3,4]

[4, 2, 3, 4]

In [ ]:
x=2
x**2
for i in [4,2,3,4]:
  print(i**2)

16
4
9
16


In [ ]:
data=np.loadtxt("/content/sample.txt")
paths=glob.glob("/content/*.txt")

In [ ]:
paths

['/content/sample file.txt',
 '/content/sample file2.txt',
 '/content/sample.txt']

In [ ]:
for i in paths:
  data=np.loadtxt(i)
  print(data)
  print(" ")

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
 
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
 
[[12. 45. 78. 23. 56.]
 [34. 67. 89. 12. 90.]
 [56. 21. 43. 65. 87.]
 [78. 34. 12. 89. 23.]
 [90. 11. 67. 32. 45.]
 [14. 58. 29. 71. 63.]
 [32. 84. 91. 17. 55.]
 [46. 38. 27. 66. 49.]
 [53. 72. 19. 88. 30.]
 [61. 40. 76. 35. 20.]]
 


In [ ]:
np.loadtxt("/content/Test.csv", delimiter=',')

array([[ 56.,  47.,  77.,  55.,  51.],
       [ 13.,  91.,  80.,  13.,  36.],
       [ 62.,  67.,  47.,  55.,  38.],
       [ 41.,  43.,  19.,  12.,  38.],
       [ 23.,  58.,  61.,  66.,  80.],
       [ 18.,  36.,  46.,  64.,  72.],
       [ 33.,  47.,  73.,  76.,  47.],
       [ 31.,  13.,  64.,  74.,  53.],
       [ 40.,  34.,  80.,  68.,  20.],
       [ 43.,  52.,  92.,  62.,  98.],
       [ 21.,  99.,  71.,  32.,  86.],
       [ 37.,  32.,  65.,  44.,  81.],
       [ 10.,  94.,  82.,  86.,  12.],
       [ 11.,  46.,  45.,  86.,  27.],
       [ 55.,  13.,  91., 100.,  39.]])

In [ ]:
np.loadtxt("/content/Test.tsv", delimiter='\t')

<ipython-input-59-90fc06c35168>:1: UserWarning: loadtxt: input contained no data: "/content/Test.tsv"
  np.loadtxt("/content/Test.tsv", delimiter='\t')


array([], dtype=float64)

In [ ]:
data=np.random.randint(0,10,5)

In [ ]:
data

array([4, 5, 5, 0, 2])

In [ ]:
data.cumsum()

array([ 4,  9, 14, 14, 16])

In [ ]:
data.cumprod()

array([  4,  20, 100,   0,   0])

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[8, 3, 0],
       [6, 4, 6],
       [0, 8, 1]])

In [ ]:
data.cumsum(axis=1)

array([[ 8, 11, 11],
       [ 6, 10, 16],
       [ 0,  8,  9]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a=np.random.choice([10,20,30,40,50],size=3)
a

array([20, 20, 30])

In [ ]:
a=np.random.choice([10,20,30,40,50],size=3,replace=True)
a

array([50, 50, 10])

In [ ]:
a=np.random.choice([10,20,30,40,50],size=3,replace=False)
a

array([20, 30, 40])